services:
  - type: web
    name: mangal-view
    runtime: docker
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        value: mangalview2026secretkey
      - key: DB_PATH
        value: /data/users.db
